[2023-12-20T18:08:04.355+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crimes_dag.create_cluster scheduled__2023-12-10T00:00:00+00:00 [queued]>
[2023-12-20T18:08:04.368+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crimes_dag.create_cluster scheduled__2023-12-10T00:00:00+00:00 [queued]>
[2023-12-20T18:08:04.369+0000] {taskinstance.py:1361} INFO - Starting attempt 7 of 7
[2023-12-20T18:08:04.387+0000] {taskinstance.py:1382} INFO - Executing <Task(DataprocCreateClusterOperator): create_cluster> on 2023-12-10 00:00:00+00:00
[2023-12-20T18:08:04.398+0000] {standard_task_runner.py:57} INFO - Started process 6428 to run task
[2023-12-20T18:08:04.404+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'crimes_dag', 'create_cluster', 'scheduled__2023-12-10T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/crime_dag.py', '--cfg-path', '/tmp/tmprqgi9hxz']
[2023-12-20T18:08:04.408+0000] {standard_task_runner.py:85} INFO - Job 53: Subtask create_cluster
[2023-12-20T18:08:04.480+0000] {task_command.py:416} INFO - Running <TaskInstance: crimes_dag.create_cluster scheduled__2023-12-10T00:00:00+00:00 [running]> on host d2fdd2505514
[2023-12-20T18:08:04.602+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crimes_dag' AIRFLOW_CTX_TASK_ID='create_cluster' AIRFLOW_CTX_EXECUTION_DATE='2023-12-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-10T00:00:00+00:00'
[2023-12-20T18:08:04.604+0000] {dataproc.py:637} INFO - Creating cluster: crimes-cluster
[2023-12-20T18:08:04.617+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-12-20T18:08:04.623+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-12-20T18:08:54.972+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-12-20T18:08:54.994+0000] {process_utils.py:131} INFO - Sending 15 to group 6428. PIDs of all processes in the group: [6428]
[2023-12-20T18:08:54.999+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 6428
[2023-12-20T18:08:55.003+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-12-20T18:09:55.038+0000] {process_utils.py:149} WARNING - process psutil.Process(pid=6428, name='airflow task ru', status='sleeping', started='18:08:03') did not respond to SIGTERM. Trying SIGKILL
[2023-12-20T18:09:55.079+0000] {process_utils.py:86} INFO - Sending the signal 9 to group 6428
[2023-12-20T18:09:55.095+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=6428, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='18:08:03') (6428) terminated with exit code -9
[2023-12-20T18:09:55.097+0000] {standard_task_runner.py:172} ERROR - Job 53 was killed before it finished (likely due to running out of memory)
